apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotspot-ingestion
spec:
  selector:
    matchLabels:
      app: hotspot-ingestion
  template:
    metadata:
      labels:
        app: hotspot-ingestion
    spec:
      containers:
      - name: hotspot-ingestion
        image: ghcr.io/project-hotspot/hotspot-ingestion:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "1"
          requests:
            memory: "64Mi"
            cpu: "0.5"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hotspot-ingestion
spec:
  type: LoadBalancer
  selector:
    app: hotspot-ingestion
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hotspot-ingestion
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hotspot-ingestion
  minReplicas: 1
  maxReplicas: 100
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50